### ISSUE TITLE
Multi line @include suggestion

### ISSUE THREAD

**Issue by andrewdworn** [RobinRadic/blade-extensions#1]
That looks like a promising extension!

The multi line array definition enlightened me that I always wanted a multi line <code>@include</code>, but in plain blade it is not possible, as far as I know.

So instead of this:
<pre><code>@include('some.route', array('a'=>'bunch','of'=>'parameters','to'=>'pass','on'=>'here','in'=>'only','one'=>'line')</code></pre>
One could use a briefer one:
<pre><code>@include('some.route', array(
    'a'=>'bunch',
    'of'=>'parameters',
    'to'=>'pass',
    'on'=>'here',
    'but'=>'in',
    'multiple'=>'lines')</code></pre>

Please consider this idea, and good work finishing the extension!

**Comment by RobinRadic** [comment]
```php
@set($myarr, [
    'a'=>'bunch',
    'of'=>'parameters',
    'to'=>'pass',
    'on'=>'here',
    'but'=>'in',
    'multiple'=>'lines'
]);
```
and lots of other variants work now
