### ISSUE TITLE
Using @set right after @foreach throws FatalErrorException

### ISSUE THREAD

**Issue by van100j** [RobinRadic/blade-extensions#11]
Using ```@set``` right after ```@foreach``` throws ```FatalErrorException in daf5b1ff7385a6726aacd9e899b61add line 42:
syntax error, unexpected '<'``` 

For example:

```@foreach( $categories as $c )```
```@set('products_cnt', count($c->products))```

throws error, but putting ```@set``` within any tag

```@foreach( $categories as $cat )```
```<i>@set('products_cnt', count($c->products))</i>```

works just fine

**Comment by RobinRadic** [comment]
thanks, will fix the issue in the next couple of days.

**Comment by RobinRadic** [comment]
fixed with 3.0.0. make sure to re-publish the config file
