### ISSUE TITLE
The error in the location of config / blade_extensions.php

### ISSUE THREAD

**Issue by greal** [RobinRadic/blade-extensions#13]
Good day!
When the `composer update` pops up an error:

```
Error Output: PHP Warning:  Uncaught exception 'ErrorException' with message 'require(/mysite/vendor/radic/blade-extensions/src/resources/config/blade_extensions.php): failed t  
  o open stream: No such file or directory' in /mysite/vendor/laravel/fra  
  mework/src/Illuminate/Support/ServiceProvider.php:64 
```

I decided to move a folder in the appropriate directory.

**Comment by RobinRadic** [comment]
It looks to me like you have somehow got the develop version of the package. Make sure you have v2.1.0 installed. Not dev-master or dev-develop.

**Comment by greal** [comment]
Hmm, I have all the default, I created a new project, added to `composer.json` 
```
"radic/blade-extensions": "2.*"
```
and I have issued this error. 
Please tell me what I did wrong?

**Comment by RobinRadic** [comment]
tagged v2.1.1 which fixes the issue. The problem was a dependency that was updated today

**Comment by greal** [comment]
Ok! Thank you! )
