### ISSUE TITLE
Laravel 5.0.32 Update Break

### ISSUE THREAD

**Issue by palamike** [RobinRadic/blade-extensions#18]
After I update to laravel 5.0.32. I found this error. 

PHP Warning:  Uncaught exception 'ErrorException' with message 'require(D:\dev\project\vendor\radic\blade-extensions\src\resources\config\blade_extensions.php): failed to open stre
am: No such file or directory' in D:\dev\project\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php:64

So, I work around by copy resources folder into the src folder. 

Please help to fix.

**Comment by Syra** [comment]
Hi,
I have similiar problem. Check it out https://github.com/RobinRadic/blade-extensions/pull/17.
I think as temprorary solution you can add to your compoer.json require section next line
```"laradic/support": "^1.2.5"```.

Best wishes,
Alex

**Comment by RobinRadic** [comment]
3.0.1 fixed this

**Comment by Syra** [comment]
Thanks for fix.

**Comment by palamike** [comment]
Thank You.
