### ISSUE TITLE
Don't Work with Laravel 5.1

### ISSUE THREAD

**Issue by headersalreadysent** [RobinRadic/blade-extensions#20]
laradic/support wants 5.0.* and laravel 5.1 cant work with blade-extensions.
Any update is near?

**Comment by RobinRadic** [comment]
sure, i'l push an update soon. can't name any time/date but should be within the next few days.

**Comment by Syra** [comment]
Hello,
Nice to hear it. 
Just say if you need any help with that.

Thanks,
Alex

**Comment by lahaxearnaud** [comment]
Hello,

It will be great !

Thanks,

Arnaud

**Comment by jernejrostan** [comment]
Did anything changed that much in 5.1 that blade-extensions is so dependent on? Any release date of update? :)

**Comment by younes0** [comment]
Check https://github.com/crhayes/blade-partials/issues/7

**Comment by RobinRadic** [comment]
@jernejrostan Laravel 5.1 removed some methods from the BladeCompiler class that provided regex strings for simple directive matchers, which was the main culprit.

**Comment by RobinRadic** [comment]
@Syra Thanks Alex. Altough this issue is now fixed, PR's are always welcome :)
