### ISSUE TITLE
@macro rendered in view again

### ISSUE THREAD

**Issue by samijnih** [RobinRadic/blade-extensions#23]
I'm sorry for the issue but even with the latest comit, I always have this error. I copied pasted the file you edited in the latest commit into vendor/radic/blade-extensions/src/

It renders this when I call @domacro('test', 'hey') :

	@macro('test', $test) return ''; @endmacro @domacro('test', 'hey')

my index.blade.php containing :

	@macro('test', $test)
		return '<img src="' . $test . '" />';
	@endmacro

When I keep '\Radic\BladeExtensions\Directives\MacroDirectives::attach($this->app)' in AppServiceProvider.php, I have the error
When I remove '\Radic\BladeExtensions\Directives\MacroDirectives::attach($this->app)' in AppServiceProvider.php, I have the error
I also renamed the form alias to 'form' or 'Form' and it doesn't change anything

**Comment by samijnih** [comment]
up

**Comment by RobinRadic** [comment]
a bit busy lately, il get to it as soon as i got time for it

**Comment by RobinRadic** [comment]
Sorry for the delay. 

Latest commit should fix the issue. New patched version up in a sec.

If you encounter any other problems let me know.

Thanks.
