### ISSUE TITLE
Issue with multiple @render 

### ISSUE THREAD

**Issue by moon0326** [RobinRadic/blade-extensions#26]
Hi,

It looks like the following code doesn't work as expected.

```html
<form method="@render('formMethod', 'POST')" action="@render('formAction', 'd')" id="@render('formId', 'modalForm')">
```

I got "syntax error, unexpected '" action="' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ';'"

When I look at the actual php file (compiled), I see the following php.

```php
<form method="<?php echo \Radic\BladeExtensions\Helpers\Partial::renderBlock('formMethod', 'POST')" action="@render('formAction', 'd'); ?>"
                id="<?php echo \Radic\BladeExtensions\Helpers\Partial::renderBlock('formId', 'modalForm'); ?>">
```

As you see the @render for the 'action' didn't get converted.

Am I doing something wrong?

**Comment by RobinRadic** [comment]
@render is depracted and @embed should be used. Make sure you have the latest version.

**Comment by moon0326** [comment]
@RobinRadic  good to know. Where can I found the documentation?

**Comment by RobinRadic** [comment]
The readme has an example which should be sufficient. If it lacks anything or if you have any questions feel free to create a new issue about it.
