### ISSUE TITLE
Why @sections inside @embed doesn't have access to global variables? 

### ISSUE THREAD

**Issue by whipsterCZ** [RobinRadic/blade-extensions#28]
It is possible to make these variables accessible? 
It is pain to write code like this

@embed('components.box', ['offices'=>$offices, 'labels'=>$labels, 'years'=>$years ......]  )

**Comment by RobinRadic** [comment]
this is as intended. use `@include` otherwise. 
or
`@embed(´box´, compact(´offices´, ´labels´, ´years´))`

**Comment by whipsterCZ** [comment]
Thanks.

@embed(´box´, compact(´offices´, ´labels´, ´years´)) doesn't work, I have already tried it..

Parse Error 
syntax error, unexpected ';'  (line 18)


10:    <?php $__env->stopSection(); ?>
11:    
12:    <?php $__env->startSection('content'); ?>
13:    
14:        <?php app('blade.embedding')->open('inspinia.box', compact('offices','years','quarters')->insert(<<<'EOT'
15:    )
16:        
17:    EOT
18:            )->close(); ?>
19:
