### ISSUE TITLE
@embedGlobal

### ISSUE THREAD

**Issue by whipsterCZ** [RobinRadic/blade-extensions#29]
Hi
macro @embed is great. - Thank you

What about creating new macro **@embedGlobal**  - embed with global context which can directly access global variables in template?
Similar as  `{% embed %}` in TWIG,  where this is standard behaviour

Thanks you.

**Comment by whipsterCZ** [comment]
maybe current   @embed should be @component
and @embedWithGlobal should be @embed or @template

what you say?

**Comment by RobinRadic** [comment]
I left out the environment variables on purpose to enable the possibility of using `@section` and `@yield` seperately to avoid name conflicts. 

It'll be a bit tricky to get the behaviour you want. In any case, to completely allow all globals will not work i think. When i got time i'll look up how to implement something that will do something similar to what your suggesting.

**Comment by RobinRadic** [comment]
When done, i'll tag a new version that includes the changes.

Now `@embed` will include all global variables. Any variables passed as argument with a similar name will override the globals inside the embedded view; `@embed('view', ['title' => 'overides_global'])`.

**Comment by whipsterCZ** [comment]
Thank you for great helpers and support :)
