### ISSUE TITLE
@embed with compact()    parse error

### ISSUE THREAD

**Issue by whipsterCZ** [RobinRadic/blade-extensions#30]
@embed('inspinia.box', compact('people'))
		@section('title','People');
    @endembed

causes Parse Error - syntax error, unexpected ';'  
 
![screenshot](https://cloud.githubusercontent.com/assets/567430/9653941/5efe7194-5227-11e5-9380-8087c212a1e3.png)

**Comment by RobinRadic** [comment]
Same as reported in #27 . Will fix soon, closing this one keeping #27 open.
