### ISSUE TITLE
@include is not working inside @embed 

### ISSUE THREAD

**Issue by whipsterCZ** [RobinRadic/blade-extensions#35]
I have this code
~~~
@embed('inspinia.box')
	@section('title','Edit User')
	@section('content')
		@include('admin.users._form')
	@endsection()
@endembed
~~~

it is failing with this error message:
Call to undefined method `Radic\BladeExtensions\Helpers\EmbedStack::make()`
at  **line:4**
~~~
 2:   <?php $__env->startSection('title','Edit User'); ?>
 3:   <?php $__env->startSection('content'); ?>
 4:   <?php echo $__env->make('admin.users._form', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
 5:   <?php $__env->stopSection(); ?>



~~~

**Comment by RobinRadic** [comment]
until i fix this, this should work:

somewhere in some service provider's boot function, add:
`$this->app['blade.helpers']->put('embed', \App\Overide\EmbedStacker::class);`

**Comment by whipsterCZ** [comment]
Thank you

Unfortunately this fix doesn't work

it throws 
~~~
Call to a member function start() on string
~~~

on code
~~~
 <?php app('blade.helpers')->get('embed')->start('inspinia._box'); ?>
~~~

-------------

the solution is add this method directly to `Radic\BladeExtensions\Helpers\EmbedStack`

~~~
class EmbedStack implements Stack {
...
    protected function make($view, $params=[]){
        return app('view')->make($view, $params);
    }
~~~

Can you make tests and add push this to the repository?

**Comment by RobinRadic** [comment]
The EmbedStack class is used in blade views and replaces the `$__env` variable, which is the `View` factory instance. For some reason, i forgot to implement the contract. Its now fixed and it correctly implements the view factory contract.
