### ISSUE TITLE
Composer requiring problem

### ISSUE THREAD

**Issue by evsign** [RobinRadic/blade-extensions#37]
Hi, when i try to install package i get error:
![error](http://dl1.joxi.net/drive/0002/2750/154302/151218/d6e38f54c4.jpg)

**Comment by HeuJung** [comment]
similar errors.

**Comment by evsign** [comment]
Just add `"danielstjules/stringy": "1.9.*"` to composer, but i think this is a bad solution because forcing to use old version of package.

**Comment by RobinRadic** [comment]
Should be resolved in `~6.1`
