### ISSUE TITLE
BLADE-42 ⁃ Incompatible with other directives that use `$__env`

### ISSUE THREAD

**Issue by unstoppablecarl** [RobinRadic/blade-extensions#39]
Out of the box code generated from blade templates includes the variable `$__env`, assigned to an instance of `Illuminate\View\Factory`.

When using blade-extensions `$__env` is assigned to an instance of `Radic\BladeExtensions\Helpers\EmbedStack`. This class has _most_ of the same methods as `Illuminate\View\Factory`, but it does not have them all. I have a directive that uses `$__env->hasSection($section)`. This method is **not** in the `Radic\BladeExtensions\Helpers\EmbedStack` class.

To ensure the default behavior of `$__env` is maintained when using blade-extensions the following could be added to `Radic\BladeExtensions\Helpers\EmbedStack`.

``` php
    /**
     * Dynamically call the view factory instance.
     *
     * @param  string  $method
     * @param  array   $parameters
     * @return mixed
     */
    public function __call($method, $parameters)
    {
        return call_user_func_array([$this->viewFactory, $method], $parameters);
    }
```

**Comment by RobinRadic** [comment]
Yeah using that magic method would work. However, that $__env replacement should only happen inside `@embed` iirc. I will review the code once i have time and correct any wrong behaviour as well as adding the magic method, just to make sure all methods will work

**Comment by unstoppablecarl** [comment]
That is exactly where I observed this behavior. I was not sure if it used `Radic\BladeExtensions\Helpers\EmbedStack` all the time or only in extensions.

**Comment by RobinRadic** [comment]
Currently i think i will not implement the magic method. The reason why embedding is capable of re-using section names without interfering with each other is because it doesn't use the view factory. Altough it's probably not going to cause problems, the current way is the intended behaviour.

However, i'd still like to make this possible. How about i bind the `EmbedStack`  to `blade.extensions.embedstack`. You'll be able to something like

```php
namespace App\Blade;
class EmbedStackExt extends \Radic\BladeExtensions\Helpers\EmbedStack {
    public function __call($method, $parameters)
    {
        return call_user_func_array([$this->viewFactory, $method], $parameters);
    }
}
```

```php
class AppServiceProvider extends ServiceProvider {
public function register(){
    $this->app->register('blade.extensions.embedstack', \App\Blade\EmbedStack::class);
}
```

**Comment by RobinRadic** [comment]
It's currently possible to extend in a similair method as shown above, however, you'd have to extend `EmbedStacker` class as well, as it's responsible for instanceiating the `EmbedStack` class.
