### ISSUE TITLE
BladeExtenderTrait cause ReflectionException: Class blade.compiler does not exist

### ISSUE THREAD

**Issue by whipsterCZ** [RobinRadic/blade-extensions#40]
Trait *BladeExtenderTrait* throws exception
`ReflectionException in Container.php line 741: Class blade.compiler does not exist`

```
$blade      = $app->make('blade.compiler'); //error
//should be 
$blade      = $app->make('view')->getEngineResolver()->resolve('blade')->getCompiler();
```

**Comment by younes0** [comment]
Same error after composer update
>
 - Removing laravel/framework (v5.1.26)
 - Installing laravel/framework (v5.1.28)
 - Removing radic/blade-extensions (6.0.5)
 - Installing radic/blade-extensions (6.1.0)

**Comment by RobinRadic** [comment]
@younes0 his change fixed this

**Comment by whipsterCZ** [comment]
Thanks
