### ISSUE TITLE
release 6.1 is broken!

### ISSUE THREAD

**Issue by whipsterCZ** [RobinRadic/blade-extensions#42]
problem is in dependency on  `Sebwite/support`

PHP error 
`Class 'Sebwite\Support\Vendor\Stringy' not found`

in Sebwite .gitignore is *vendor/**

**Comment by RobinRadic** [comment]
are you on windows?

**Comment by whipsterCZ** [comment]
Mac

**Comment by RobinRadic** [comment]
should be able to resolve this until the fix is implented by adding `sebwite/support: 1.0.$` in the root composer file. Where `$`  should be an earlier version that worked, will check later which one that actually was.

**Comment by timothyrowan** [comment]
just tested. sebwite/support (1.0.12) is the latest that doesn't throw the error

**Comment by RobinRadic** [comment]
awesome. i'l close this one then
