### ISSUE TITLE
Minification in compile time

### ISSUE THREAD

**Issue by TheAliAbbasi** [RobinRadic/blade-extensions#46]
Is there anyways to make minification at view's compile time? I tried to use https://github.com/GrahamCampbell/Laravel-HTMLMin package to minify views at compile time but it breaks extensions from this package

**Comment by RobinRadic** [comment]
Not entirely sure what you mean. If you want to integrate your own minification logic using the directives the `blade-extensions` package is using, you could alter the `config/blade_extensions.php` config and add `minify` and `endminify` items to the `blacklist` array eg:

```php
<?php
/**
 * Part of Radic - Blade Extensions
 *
 * @author         Robin Radic
 * @license        MIT License - http://radic.mit-license.org
 * @copyright  (c) 2011-2015, Robin Radic - Radic Technologies
 * @link           http://radic.nl
 */

return array(
    /*
    |---------------------------------------------------------------------
    | Blacklisting of directives
    |---------------------------------------------------------------------
    |
    | These directives will be excluded.
    |
    */
    'blacklist' => array('minify', 'endminify')
);
```
