### ISSUE TITLE
Leave a single space between tags in minification

### ISSUE THREAD

**Issue by TheAliAbbasi** [RobinRadic/blade-extensions#47]
It would be better to leave a single space between tags in minifying process as some templates use that single space instead of margin and it would be a hassle to fix those

**Comment by RobinRadic** [comment]
Not entirely sure what you mean. If you want to integrate your own minification logic using the directives the `blade-extensions` package is using, you could alter the `config/blade_extensions.php` config and add `minify` and `endminify` items to the `blacklist` array eg:

```php
<?php
/**
 * Part of Radic - Blade Extensions
 *
 * @author         Robin Radic
 * @license        MIT License - http://radic.mit-license.org
 * @copyright  (c) 2011-2015, Robin Radic - Radic Technologies
 * @link           http://radic.nl
 */

return array(
    /*
    |---------------------------------------------------------------------
    | Blacklisting of directives
    |---------------------------------------------------------------------
    |
    | These directives will be excluded.
    |
    */
    'blacklist' => array('minify', 'endminify')
);
```

and afterwards implement your own logic. 

Alternatively you could override/alter the `blade.helpers` binding, which containers the `Radic\BladeExtensions\Helpers\HelperRepository` class which in turn contains the `Radic\BladeExtensions\Helpers\Minifier` class that is responsible for minification.

It's failry easy to replace any of the minifaction logic and replace it with your own/vendor library. Feel free to create another issue if need more help.
