### ISSUE TITLE
publishing config returns an empty array

### ISSUE THREAD

**Issue by samijnih** [RobinRadic/blade-extensions#50]
Hello,

Laravel 5.2,
Blade-exentesions 6.2

When doing `php artisan vendor:publish --provider=Radic\BladeExtensions\BladeExtensionsServiceProvider`

it returns : `Nothing to publish for tag [].`

Thanks, :)

**Comment by RobinRadic** [comment]
doesn't that mean you already have the `blade_extensions.php` file in your `config` folder?

**Comment by bullenb** [comment]
I'm getting the same and I have checked my config folder. There is no `blade_extensions.php` file.

I've also tried

```
php artisan vendor:publish --provider=Radic\BladeExtensions\BladeExtensionsServiceProvider --tag=view
```

Which returned 

> Nothing to publish for tag [view].

And failed to create the example view files in my resources/views folder. 

Thanks

**Comment by sebastiaanluca** [comment]
Has this been merged yet? Having the same issue. I can copy the config file manually though, just giving you the heads up.
