### ISSUE TITLE
Nest @minify inside another @minify

### ISSUE THREAD

**Issue by vabatta** [RobinRadic/blade-extensions#56]
Hi,

would be great if you can nest the `@minify` directive inside another `@minify` directive, as below:
`some.blade.php`

``` html
@minify('html')
  <div>
    <h4>Yayyyy!</h4>
  </div>
@endminify
```

`main.blade.php`

``` html
<script>
  @minify('js')
    var html = "@include('_some')";
  @endminify
</script>
```

Thanks!

**Comment by RobinRadic** [comment]
Quoting [@minify](https://github.com/RobinRadic/blade-extensions/blob/master/docs/directives/minify.md) documentation.

> There aren't many valid use-cases for using this directive. Check out the [alternatives](https://github.com/RobinRadic/blade-extensions/blob/master/docs/directives/minify.md#alternatives) at the bottom of the page first!
