### ISSUE TITLE
@push to parent extends inside @embed

### ISSUE THREAD

**Issue by vabatta** [RobinRadic/blade-extensions#57]
Hi,

would be great to be able to `@push` something from the `@embed` directive to the parent.
Example:
component.blade.php
```html
@yield('content')
@push('js')
  <script>alert('pushed!');</script>
@endpush
```
layout.blade.php
```html
@yield('content')
@stack('js')
```
page.blade.php
```html
@extends('layout')
@section('content')
  @embed('component')
    Should push a script!
  @endembed
@endsection
```

**Comment by RobinRadic** [comment]
this will never be possible.

the embed directive has been created in such a way that it does not share the environment. This is done on purpose. This way its possible to create sections with the same name and provides other functionality that i dont know out of the top of my head.

**Comment by vabatta** [comment]
You actually don't share anything with the environment. `@push` if used inside the component itself, actually push the content to the parent, while using it inside `@embed` push to the component. I don't see a break on the concept, or am I wrong?

**Comment by RobinRadic** [comment]
it would break:

component
```php
@yield('content')
@stack('js')
```

view
```html
@embed('component')
   @section('content')
   @show
   @push('js')
   @endpush
@endembed

<!-- somehwere else --->
@stack('js')
```

**Comment by vabatta** [comment]
@RobinRadic 
It's different from what I mean; the way you used the `@push` would actually break the directive, but if you look at https://github.com/RobinRadic/blade-extensions/issues/57#issue-165743835 you could see that it won't break.
This way would be useful to develop a modular component which could have scripts included to the parent stack, for example to the bottom of the page (as recommended in [yahoo dev](https://developer.yahoo.com/performance/rules.html#js_bottom)).

**Comment by RobinRadic** [comment]
if id implemented that, everyone using the way i mentioned will be forced to change their code. so it breaks backward compatibility.

use 
```php
view()->getFactory()->startPush('js')
```

alternatively, make a custom directive `@parentpush` or something.

**Comment by vabatta** [comment]
I've created the `@parentpush` and `@endparentpush` directives this way:
AppServiceProvider.php
```php
Blade::directive('parentpush', function($expression) {
  return '<?php view()->startPush(' . $expression . '); ?>';
});

Blade::directive('endparentpush', function() {
  return '<?php view()->stopPush(); ?>';
});
```
And used this way:
component.blade.php
```html
@yield('content')
@parentpush('js')
  <script>alert('pushed 1!');</script>
  @stack('js')
@endparentpush
```
layout.blade.php
```html
@yield('content')
@stack('js')
```
page.blade.php
```html
@extends('layout')
@section('content')
  @embed('component')
    Should push two scripts!
    @push('js')
      <script>alert('pushed 2!');</script>
    @endpush
  @endembed
@endsection
```

Got perfectly working!
