### ISSUE TITLE
v3.0 Broken Dependancy Tree?

### ISSUE THREAD

**Issue by MrToLLi** [RobinRadic/blade-extensions#58]
Hi there,

I'm trying to use an older version of the package (v3.0) as we currently only support Laravel 5.0. When I do a composer update I get the following

<img width="662" alt="screen shot 2016-09-23 at 09 41 24" src="https://cloud.githubusercontent.com/assets/2144722/18779857/ac823060-8172-11e6-946f-808f23caca7e.png">

Looking at the composer.json for v3 you can see the dependancy as follows

<img width="269" alt="screen shot 2016-09-23 at 09 41 34" src="https://cloud.githubusercontent.com/assets/2144722/18779877/c85e354a-8172-11e6-9275-1e55996a8e06.png">

However checking on Packagist [here](https://packagist.org/packages/laradic/support) it only shows v1.0.0 which requires PHP >= 5.5.9? See below...

<img width="268" alt="screen shot 2016-09-23 at 09 44 56" src="https://cloud.githubusercontent.com/assets/2144722/18779965/38a71c7c-8173-11e6-9b02-21fb4404c763.png">

This means that v3.0 can never be installed as it can't resolve a dependancy which doesn't exist. Am I missing something or has support for v3.0 been dropped? 

Thanks

**Comment by RobinRadic** [comment]
Please read [this issue](https://github.com/laradic/support/issues/1) for the answer to your problem.

**Comment by RobinRadic** [comment]
this issue is fixed with `7.0.0` release.
Just use `7.0.0`
