### ISSUE TITLE
not working on Laravel 5.4 even when using dev-develop branch

### ISSUE THREAD

**Issue by vesper8** [RobinRadic/blade-extensions#65]
Hi there,

I hadn't used your package for a while and tried to use it just now. I quickly saw that there was a conflict between the new $loop changes introduced in 5.3. So I came here to see if you had made any changes and saw you were working on a new 7.0 version that would fix all this!

So I switched to the develop branch and tried adding "radic/blade-extensions": "~7.0"
but that didn't work. Then I changed that to dev-develop and that worked.

I got the latest files, cleared all cache and tried again but it's still giving me an error about Undefined index: iteration when trying to use $loop->iteration inside a @foreach loop

I published your blade-extensions config file and added a section for 5.4, basically just duplicated the 5.3 under version_overrides but that still didn't work. I thought maybe you're not merging the config so I also modified the blade-extensions.php file inside the vendor folder.. but still no go.

Can you tell me what I need to do to use your extension with 5.4 if I'm using your latest development branch?

Much appreciated!

Thanks!

**Comment by RobinRadic** [comment]
sorry for the late response, but this might do the trick

```php

return [
    'mode'              => 'auto',
    'directives'        => [
    ],
    'version_overrides' => [
        // add 5.4
        '5.4' => [
            'foreach'    => null,
            'endforeach' => null,
            'break'      => null,
            'continue'   => null,
        ],
    ],
];
```

**Comment by RobinRadic** [comment]
in the config file `blade-extensions.php`

**Comment by RobinRadic** [comment]
@vesper8 https://travis-ci.org/RobinRadic/blade-extensions/builds/203254265
This should be working. Will tag `7.0.0` after some more adjustments / tests.
```json
"radic/blade-extensions": "dev-develop as 7.0.0"
```
