### ISSUE TITLE
Laravel 5.4 heredoc error

### ISSUE THREAD

**Issue by codemonkeynorth** [RobinRadic/blade-extensions#66]
I'm getting this when trying to use @embed

@embed('test1')
@section('subtitle','test')
@endembed

`syntax error, unexpected end of file, expecting variable (T_VARIABLE) or heredoc end (T_END_HEREDOC) or ${ (T_DOLLAR_OPEN_CURLY_BRACES) or {$ (T_CURLY_OPEN)`

generated template
```php
<?php app('blade-extensions.helpers')->get('embed')->start('test1'); ?>
<?php app('blade-extensions.helpers')->get('embed')->current()->setData($__data)->setContent(<<<'EOT_'

<?php $__env->startSection('subtitle', 'test'); ?>

\EOT_
); ?>
<?php app('blade-extensions.helpers')->get('embed')->end(); ?>
```

if i go in and remove the \ before the EOT, i then get a different error
`Call to a member function start() on null`

please advise.. is it my PHP version? 5.6.25
thanks

**Comment by RobinRadic** [comment]
this is actually already fixed in [this](github.com/RobinRadic/blade-extensions/commit/9468185e2621e0d304394a9cf8cce349ef9f5afc?diff=unified#diff-9d8b5f71f608e79332d6f460bc388492) commit
