### ISSUE TITLE
Not working on Laravel 5.6

### ISSUE THREAD

**Issue by jrmessias** [RobinRadic/blade-extensions#74]
Do you have plan to add support for Laravel 5.6?

**Comment by RobinRadic** [comment]
I will release a new version with 5.6 compatibility by the end of the week.

**Comment by RobinRadic** [comment]
@jrmessias @jayenne I installed blade-extensions on a fresh 5.6, it worked without any problems. All tests also worked (after updating dev dependencies). 

Could you provide additional information (with error log) on what problems you encountered?
