### ISSUE TITLE
Call to a member function newLoop() on null 

### ISSUE THREAD

**Issue by greal** [RobinRadic/blade-extensions#75]
Good day! 

I want to use the helper `even`, if the view is not in the cache, it works successfully as soon as the error is cached:

```
Call to a member function newLoop() on null 
```

tell me please how to solve this?

**Comment by RobinRadic** [comment]
Hello!

Please provide:
- a list of steps to replicate this error. 
- the laravel and blade-extensions versions in use
- stack trace

**Comment by RobinRadic** [comment]
7.1.0 should fix this
