### ISSUE TITLE
PHP 7.3 sometimes triggers a show-stopping error in the error handling of the handle function in AbstractDirective

### ISSUE THREAD

**Issue by prurigro** [RobinRadic/blade-extensions#78]
The error is `array_flip(): Can only flip STRING and INTEGER values!` and it's triggered by this line of `src/Directives/AbstractDirective.php`: `$error = array_flip(get_defined_constants(true)['pcre'])[preg_last_error()];`. I can stop the error (and my project loads correctly) if I remove the error handling lines of that function.

Being that this only occurs on certain files, I suspect the output set of preg_last_error() has changed in 7.3, and that it only gets triggered when certain conditions cause the output to look a certain way. If I load the content of the blade causing an issue into a blade that doesn't have an issue, it'll both get the issue, and continue to have it after I revert my changes. If I then remove error handling from the handle function, load the page successfully, then re-add it, the error goes away (so when the above error is triggered by something else, it then seems to trigger itself).

**Comment by dweinerATL** [comment]
I get the same error, which is preventing me from moving my application to PHP 7.3

**Comment by prurigro** [comment]
Thanks everyone!
